<template>
  <div>
    <bc-select :clearable="true"
               :value="value"
               :placeholder="placeholder"
               :datalist="datalist"
               :props="props"
               :labelFn="labelFn"
               :pageSize="pageSize"></bc-select>
  </div>
</template>
<script>
import bcSelect from "./index";
import { accountLabel } from "@/util/common";
export default {
  data() {
    return {
      value: 0,
      placeholder: "请选择广告主",
      datalist: [
        {
          "id": 0,
          "thirdName": "全部",
          "alias": "全部",
          "thirdLoginName": "9226986",
          "thirdAccountName": "全部",
          "thirdAccountId": 0,
          "platformId": 34,
          "platformName": "广点通",
          "productName": "",
          "managerName": ""
        }, {
          "id": 2838,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9226986",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9226986",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2839,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9344834",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9344834",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2840,
          "thirdName": "9344872",
          "thirdLoginName": "9344872",
          "thirdAccountId": "-1",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2841,
          "thirdName": "9344880",
          "thirdLoginName": "9344880",
          "thirdAccountId": "-1",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2842,
          "thirdName": "9345257",
          "thirdLoginName": "9345257",
          "thirdAccountId": "-1",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2948,
          "thirdName": "9471760",
          "thirdLoginName": "9471760",
          "thirdAccountName": "北京严肃科技有限公司",
          "thirdAccountId": "9471760",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "刷刷看",
          "managerName": "孟杨杨"
        }, {
          "id": 2949,
          "thirdName": "9464799",
          "thirdLoginName": "9464799",
          "thirdAccountName": "北京密境和风科技有限公司",
          "thirdAccountId": "9464799",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "花椒直播",
          "managerName": "张军英"
        }, {
          "id": 2950,
          "thirdName": "9460106",
          "thirdLoginName": "9460106",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9460106",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2951,
          "thirdName": "9460080",
          "thirdLoginName": "9460080",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9460080",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2952,
          "thirdName": "9451623",
          "thirdLoginName": "9451623",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9451623",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 2953,
          "thirdName": "百传测试户",
          "alias": "百传测试户",
          "thirdLoginName": "4447986",
          "thirdAccountName": "北京百传中云信息科技有限公司",
          "thirdAccountId": "4447986",
          "platformId": 34,
          "platformName": "广点通",
          "managerName": "测试"
        }, {
          "id": 2954,
          "thirdName": "2769448",
          "thirdLoginName": "2769448",
          "thirdAccountName": "北京电视台",
          "thirdAccountId": "2769448",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 2955,
          "thirdName": "2739822",
          "thirdLoginName": "2739822",
          "thirdAccountName": "腾讯科技(深圳)有限公司",
          "thirdAccountId": "2739822",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 2956,
          "thirdName": "2632518",
          "thirdLoginName": "2632518",
          "thirdAccountName": "广州优视网络科技有限公司",
          "thirdAccountId": "2632518",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 2957,
          "thirdName": "2632008",
          "thirdLoginName": "2632008",
          "thirdAccountName": "世纪保众(北京)网络科技有限公司",
          "thirdAccountId": "2632008",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 2961,
          "thirdName": "北京淘友天下科技发展有限公司",
          "alias": "北京淘友天下科技发展有限公司",
          "thirdLoginName": "9561039",
          "thirdAccountName": "北京淘友天下科技发展有限公司",
          "thirdAccountId": "9561039",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "脉脉",
          "managerName": "孟杨杨"
        }, {
          "id": 2962,
          "thirdName": "北京淘友天下科技发展有限公司",
          "alias": "北京淘友天下科技发展有限公司",
          "thirdLoginName": "9561029",
          "thirdAccountName": "北京淘友天下科技发展有限公司",
          "thirdAccountId": "9561029",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "脉脉",
          "managerName": "孟杨杨"
        }, {
          "id": 2963,
          "thirdName": "北京淘友天下科技发展有限公司",
          "alias": "北京淘友天下科技发展有限公司",
          "thirdLoginName": "9559671",
          "thirdAccountName": "北京淘友天下科技发展有限公司",
          "thirdAccountId": "9559671",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "脉脉",
          "managerName": "张军英"
        }, {
          "id": 2964,
          "thirdName": "北京淘友天下科技发展有限公司",
          "alias": "北京淘友天下科技发展有限公司",
          "thirdLoginName": "9559664",
          "thirdAccountName": "北京淘友天下科技发展有限公司",
          "thirdAccountId": "9559664",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "脉脉",
          "managerName": "孟杨杨"
        }, {
          "id": 2965,
          "thirdName": "杭州递金网络科技有限公司",
          "alias": "杭州递金网络科技有限公司",
          "thirdLoginName": "9552639",
          "thirdAccountName": "杭州递金网络科技有限公司",
          "thirdAccountId": "9552639",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "社保掌上通"
        }, {
          "id": 2966,
          "thirdName": "杭州递金网络科技有限公司",
          "alias": "杭州递金网络科技有限公司",
          "thirdLoginName": "9552528",
          "thirdAccountName": "杭州递金网络科技有限公司",
          "thirdAccountId": "9552528",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "闪电公积金"
        }, {
          "id": 2967,
          "thirdName": "北京淘友天下科技发展有限公司",
          "alias": "北京淘友天下科技发展有限公司",
          "thirdLoginName": "9550054",
          "thirdAccountName": "北京淘友天下科技发展有限公司",
          "thirdAccountId": "9550054",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "脉脉",
          "managerName": "孟杨杨"
        }, {
          "id": 3020,
          "thirdName": "杭州递金网络科技有限公司",
          "alias": "杭州递金网络科技有限公司",
          "thirdLoginName": "9590025",
          "thirdAccountName": "杭州递金网络科技有限公司",
          "thirdAccountId": "9590025",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "挖财信用卡管家"
        }, {
          "id": 3045,
          "thirdName": "北京严肃科技有限公司",
          "alias": "北京严肃科技有限公司",
          "thirdLoginName": "9639961",
          "thirdAccountName": "北京严肃科技有限公司",
          "thirdAccountId": "9639961",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "刷刷看"
        }, {
          "id": 3048,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9344849",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9344849",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 3071,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9698633",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9698633",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 3072,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9698369",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9698369",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 3073,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9698244",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9698244",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 3093,
          "thirdName": "北京网聘咨询有限公司",
          "alias": "北京网聘咨询有限公司",
          "thirdLoginName": "9734594",
          "thirdAccountName": "北京网聘咨询有限公司",
          "thirdAccountId": "9734594",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "智联招聘",
          "managerName": "张军英"
        }, {
          "id": 3215,
          "thirdName": "海南美高美网络科技有限公司",
          "alias": "海南美高美网络科技有限公司",
          "thirdLoginName": "9873524",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "9873524",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "土耳其方块",
          "managerName": "徐美丽"
        }, {
          "id": 3216,
          "thirdName": "北京金岩石通讯技术有限公司",
          "alias": "北京金岩石通讯技术有限公司",
          "thirdLoginName": "9867610",
          "thirdAccountName": "北京金岩石通讯技术有限公司",
          "thirdAccountId": "9867610",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "联通业务",
          "managerName": "孟杨杨"
        }, {
          "id": 3348,
          "thirdName": "海南美高美网络科技有限公司",
          "alias": "海南美高美网络科技有限公司",
          "thirdLoginName": "10011130",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "10011130",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "土耳其方块",
          "managerName": "米硕"
        }, {
          "id": 3349,
          "thirdName": "卫盈联信息技术(深圳)有限公司",
          "alias": "卫盈联信息技术(深圳)有限公司",
          "thirdLoginName": "9994548",
          "thirdAccountName": "卫盈联信息技术(深圳)有限公司",
          "thirdAccountId": "9994548",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "我来贷",
          "managerName": "米硕"
        }, {
          "id": 3365,
          "thirdName": "汕头市兽游互娱网络科技有限公司",
          "alias": "汕头市兽游互娱网络科技有限公司",
          "thirdLoginName": "10030146",
          "thirdAccountName": "汕头市兽游互娱网络科技有限公司",
          "thirdAccountId": "10030146",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "天空的魔幻城",
          "managerName": "张军英"
        }, {
          "id": 3366,
          "thirdName": "上海玄霆娱乐信息科技有限公司",
          "alias": "上海玄霆娱乐信息科技有限公司",
          "thirdLoginName": "10037893",
          "thirdAccountName": "上海玄霆娱乐信息科技有限公司",
          "thirdAccountId": "10037893",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "飞读小说",
          "managerName": "米硕"
        }, {
          "id": 3367,
          "thirdName": "霓虹闪烁(北京)网络科技有限公司",
          "alias": "霓虹闪烁(北京)网络科技有限公司",
          "thirdLoginName": "10043138",
          "thirdAccountName": "霓虹闪烁(北京)网络科技有限公司",
          "thirdAccountId": "10043138",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "抢头条",
          "managerName": "米硕"
        }, {
          "id": 3368,
          "thirdName": "北京密境和风科技有限公司",
          "alias": "北京密境和风科技有限公司",
          "thirdLoginName": "10042568",
          "thirdAccountName": "北京密境和风科技有限公司",
          "thirdAccountId": "10042568",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "花椒直播",
          "managerName": "孟杨杨"
        }, {
          "id": 3416,
          "thirdName": "北京展心展力信息科技有限公司",
          "alias": "北京展心展力信息科技有限公司",
          "thirdLoginName": "10046044",
          "thirdAccountName": "北京展心展力信息科技有限公司",
          "thirdAccountId": "10046044",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "233小游戏"
        }, {
          "id": 3437,
          "thirdName": "北京天盈九州网络技术有限公司",
          "alias": "北京天盈九州网络技术有限公司",
          "thirdLoginName": "10066991",
          "thirdAccountName": "北京天盈九州网络技术有限公司",
          "thirdAccountId": "10066991",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "翻阅小说",
          "managerName": "米硕"
        }, {
          "id": 3450,
          "thirdName": "北京严肃科技有限公司",
          "alias": "北京严肃科技有限公司",
          "thirdLoginName": "10086935",
          "thirdAccountName": "北京严肃科技有限公司",
          "thirdAccountId": "10086935",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "刷刷看",
          "managerName": "米硕"
        }, {
          "id": 3451,
          "thirdName": "浙江挖财科技有限公司",
          "alias": "浙江挖财科技有限公司",
          "thirdLoginName": "10049128",
          "thirdAccountName": "浙江挖财科技有限公司",
          "thirdAccountId": "10049128",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "挖财信用卡管家",
          "managerName": "王秀敏"
        }, {
          "id": 3467,
          "thirdName": "北京万友映力科技有限公司",
          "alias": "北京万友映力科技有限公司",
          "thirdLoginName": "10016685",
          "thirdAccountName": "北京万友映力科技有限公司",
          "thirdAccountId": "10016685",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "大力课堂",
          "managerName": "米硕"
        }, {
          "id": 3474,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10341976",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10341976",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3475,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10334067",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10334067",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3476,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10332986",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10332986",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3477,
          "thirdName": "10332427",
          "thirdLoginName": "10332427",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10332427",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 3571,
          "thirdName": "哈尔滨哈银消费金融有限责任公司",
          "alias": "哈尔滨哈银消费金融有限责任公司",
          "thirdLoginName": "10668019",
          "thirdAccountName": "哈尔滨哈银消费金融有限责任公司",
          "thirdAccountId": "10668019",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "有卡贷",
          "managerName": "米硕"
        }, {
          "id": 3572,
          "thirdName": "上海玄霆娱乐信息科技有限公司",
          "alias": "上海玄霆娱乐信息科技有限公司",
          "thirdLoginName": "10660823",
          "thirdAccountName": "上海玄霆娱乐信息科技有限公司",
          "thirdAccountId": "10660823",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "飞读小说",
          "managerName": "向赛琴"
        }, {
          "id": 3573,
          "thirdName": "虎扑(上海)文化传播股份有限公司",
          "alias": "虎扑(上海)文化传播股份有限公司",
          "thirdLoginName": "10656771",
          "thirdAccountName": "虎扑(上海)文化传播股份有限公司",
          "thirdAccountId": "10656771",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3574,
          "thirdName": "北京密境和风科技有限公司",
          "alias": "北京密境和风科技有限公司",
          "thirdLoginName": "10656132",
          "thirdAccountName": "北京密境和风科技有限公司",
          "thirdAccountId": "10656132",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "花椒直播",
          "managerName": "孟杨杨"
        }, {
          "id": 3575,
          "thirdName": "重庆百度小额贷款有限公司",
          "alias": "重庆百度小额贷款有限公司",
          "thirdLoginName": "10083907",
          "thirdAccountName": "重庆百度小额贷款有限公司",
          "thirdAccountId": "10083907",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "有钱花",
          "managerName": "冯静"
        }, {
          "id": 3582,
          "thirdName": "合肥番茄金融信息服务有限公司",
          "alias": "合肥番茄金融信息服务有限公司",
          "thirdLoginName": "10655811",
          "thirdAccountName": "合肥番茄金融信息服务有限公司",
          "thirdAccountId": "10655811",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "易贷到"
        }, {
          "id": 3583,
          "thirdName": "鹰隼信息科技(宁波)有限公司",
          "alias": "鹰隼信息科技(宁波)有限公司",
          "thirdLoginName": "10689328",
          "thirdAccountName": "鹰隼信息科技(宁波)有限公司",
          "thirdAccountId": "10689328",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "嗨来电",
          "managerName": "张军英"
        }, {
          "id": 3609,
          "thirdName": "海南美高美网络科技有限公司",
          "alias": "海南美高美网络科技有限公司",
          "thirdLoginName": "10727273",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "10727273",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "土耳其方块",
          "managerName": "米硕"
        }, {
          "id": 3610,
          "thirdName": "海南美高美网络科技有限公司",
          "alias": "海南美高美网络科技有限公司",
          "thirdLoginName": "10727250",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "10727250",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3620,
          "thirdName": "上海玄霆娱乐信息科技有限公司",
          "alias": "上海玄霆娱乐信息科技有限公司",
          "thirdLoginName": "10756483",
          "thirdAccountName": "上海玄霆娱乐信息科技有限公司",
          "thirdAccountId": "10756483",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3621,
          "thirdName": "上海玄霆娱乐信息科技有限公司",
          "alias": "上海玄霆娱乐信息科技有限公司",
          "thirdLoginName": "10756437",
          "thirdAccountName": "上海玄霆娱乐信息科技有限公司",
          "thirdAccountId": "10756437",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "飞读小说",
          "managerName": "向赛琴"
        }, {
          "id": 3627,
          "thirdName": "杭州艾米巴商务信息咨询有限公司",
          "alias": "杭州艾米巴商务信息咨询有限公司",
          "thirdLoginName": "10773324",
          "thirdAccountName": "杭州艾米巴商务信息咨询有限公司",
          "thirdAccountId": "10773324",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3692,
          "thirdName": "北京锋巢信息技术有限公司",
          "alias": "北京锋巢信息技术有限公司",
          "thirdLoginName": "10777080",
          "thirdAccountName": "北京锋巢信息技术有限公司",
          "thirdAccountId": "10777080",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "微购车",
          "managerName": "孟杨杨"
        }, {
          "id": 3712,
          "thirdName": "四川花音科技有限公司",
          "alias": "四川花音科技有限公司",
          "thirdLoginName": "10805077",
          "thirdAccountName": "四川花音科技有限公司",
          "thirdAccountId": "10805077",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3713,
          "thirdName": "鹰隼信息科技(宁波)有限公司",
          "alias": "鹰隼信息科技(宁波)有限公司",
          "thirdLoginName": "10805003",
          "thirdAccountName": "鹰隼信息科技(宁波)有限公司",
          "thirdAccountId": "10805003",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3714,
          "thirdName": "魔力红(深圳)网络科技有限公司",
          "alias": "魔力红(深圳)网络科技有限公司",
          "thirdLoginName": "10804953",
          "thirdAccountName": "魔力红(深圳)网络科技有限公司",
          "thirdAccountId": "10804953",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3715,
          "thirdName": "魔力红(深圳)网络科技有限公司",
          "alias": "魔力红(深圳)网络科技有限公司",
          "thirdLoginName": "10804944",
          "thirdAccountName": "魔力红(深圳)网络科技有限公司",
          "thirdAccountId": "10804944",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "护目镜",
          "managerName": "米硕"
        }, {
          "id": 3716,
          "thirdName": "鹰隼信息科技(宁波)有限公司",
          "alias": "鹰隼信息科技(宁波)有限公司",
          "thirdLoginName": "10802434",
          "thirdAccountName": "鹰隼信息科技(宁波)有限公司",
          "thirdAccountId": "10802434",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "嗨来电"
        }, {
          "id": 3723,
          "thirdName": "魔力红(深圳)网络科技有限公司",
          "alias": "魔力红(深圳)网络科技有限公司",
          "thirdLoginName": "10804966",
          "thirdAccountName": "魔力红(深圳)网络科技有限公司",
          "thirdAccountId": "10804966",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3739,
          "thirdName": "西藏美第奇互联网小额贷款有限公司",
          "alias": "西藏美第奇互联网小额贷款有限公司",
          "thirdLoginName": "10765222",
          "thirdAccountName": "西藏美第奇互联网小额贷款有限公司",
          "thirdAccountId": "10765222",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "趣满分",
          "managerName": "孟杨杨"
        }, {
          "id": 3747,
          "thirdName": "广州荔支网络技术有限公司",
          "alias": "广州荔支网络技术有限公司",
          "thirdLoginName": "10829559",
          "thirdAccountName": "广州荔支网络技术有限公司",
          "thirdAccountId": "10829559",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "荔枝",
          "managerName": "贾荟"
        }, {
          "id": 3764,
          "thirdName": "北京微字节网络科技有限公司",
          "alias": "北京微字节网络科技有限公司",
          "thirdLoginName": "10825737",
          "thirdAccountName": "北京微字节网络科技有限公司",
          "thirdAccountId": "10825737",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "住小帮",
          "managerName": "张童"
        }, {
          "id": 3765,
          "thirdName": "浙江挖财科技有限公司",
          "alias": "浙江挖财科技有限公司",
          "thirdLoginName": "10808214",
          "thirdAccountName": "浙江挖财科技有限公司",
          "thirdAccountId": "10808214",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "挖财信用卡管家",
          "managerName": "徐美丽"
        }, {
          "id": 3779,
          "thirdName": "北京空间变换科技有限公司",
          "alias": "北京空间变换科技有限公司",
          "thirdLoginName": "10805135",
          "thirdAccountName": "北京空间变换科技有限公司",
          "thirdAccountId": "10805135",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "懂车帝",
          "managerName": "孟杨杨"
        }, {
          "id": 3915,
          "thirdName": "厦门美图之家科技有限公司",
          "alias": "厦门美图之家科技有限公司",
          "thirdLoginName": "10880636",
          "thirdAccountName": "厦门美图之家科技有限公司",
          "thirdAccountId": "10880636",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "美拍",
          "managerName": "徐美丽"
        }, {
          "id": 3920,
          "thirdName": "泰州和创互联网科技小额贷款有限公司",
          "alias": "泰州和创互联网科技小额贷款有限公司",
          "thirdLoginName": "10882190",
          "thirdAccountName": "泰州和创互联网科技小额贷款有限公司",
          "thirdAccountId": "10882190",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3921,
          "thirdName": "泰州和创互联网科技小额贷款有限公司",
          "alias": "泰州和创互联网科技小额贷款有限公司",
          "thirdLoginName": "10882139",
          "thirdAccountName": "泰州和创互联网科技小额贷款有限公司",
          "thirdAccountId": "10882139",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "白鲸信用",
          "managerName": "张童"
        }, {
          "id": 3926,
          "thirdName": "北京展心展力信息科技有限公司",
          "alias": "北京展心展力信息科技有限公司",
          "thirdLoginName": "10899907",
          "thirdAccountName": "北京展心展力信息科技有限公司",
          "thirdAccountId": "10899907",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "233小游戏",
          "managerName": "王秀敏"
        }, {
          "id": 3931,
          "thirdName": "四川花音科技有限公司",
          "alias": "四川花音科技有限公司",
          "thirdLoginName": "10901295",
          "thirdAccountName": "四川花音科技有限公司",
          "thirdAccountId": "10901295",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3949,
          "thirdName": "上海基分文化传播有限公司",
          "alias": "上海基分文化传播有限公司",
          "thirdLoginName": "10911308",
          "thirdAccountName": "上海基分文化传播有限公司",
          "thirdAccountId": "10911308",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "趣头条"
        }, {
          "id": 3953,
          "thirdName": "厦门美图之家科技有限公司",
          "alias": "厦门美图之家科技有限公司",
          "thirdLoginName": "10914541",
          "thirdAccountName": "厦门美图之家科技有限公司",
          "thirdAccountId": "10914541",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3962,
          "thirdName": "北京展心展力信息科技有限公司",
          "alias": "北京展心展力信息科技有限公司",
          "thirdLoginName": "10937343",
          "thirdAccountName": "北京展心展力信息科技有限公司",
          "thirdAccountId": "10937343",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "233小游戏"
        }, {
          "id": 3970,
          "thirdName": "重庆市分众小额贷款有限公司",
          "alias": "重庆市分众小额贷款有限公司",
          "thirdLoginName": "10946972",
          "thirdAccountName": "重庆市分众小额贷款有限公司",
          "thirdAccountId": "10946972",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3971,
          "thirdName": "重庆市分众小额贷款有限公司",
          "alias": "重庆市分众小额贷款有限公司",
          "thirdLoginName": "10945879",
          "thirdAccountName": "重庆市分众小额贷款有限公司",
          "thirdAccountId": "10945879",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 3981,
          "thirdName": "合肥番茄金融信息服务有限公司",
          "alias": "合肥番茄金融信息服务有限公司",
          "thirdLoginName": "10949850",
          "thirdAccountName": "合肥番茄金融信息服务有限公司",
          "thirdAccountId": "10949850",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "易贷到"
        }, {
          "id": 3990,
          "thirdName": "上海拍拍贷金融信息服务有限公司",
          "alias": "上海拍拍贷金融信息服务有限公司",
          "thirdLoginName": "10955226",
          "thirdAccountName": "上海拍拍贷金融信息服务有限公司",
          "thirdAccountId": "10955226",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "拍拍贷"
        }, {
          "id": 3991,
          "thirdName": "深圳市汇庄金融服务有限公司",
          "alias": "深圳市汇庄金融服务有限公司",
          "thirdLoginName": "10820554",
          "thirdAccountName": "深圳市汇庄金融服务有限公司",
          "thirdAccountId": "10820554",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "点点APP",
          "managerName": "申淼"
        }, {
          "id": 4007,
          "thirdName": "深圳市汇庄金融服务有限公司",
          "alias": "深圳市汇庄金融服务有限公司",
          "thirdLoginName": "10972591",
          "thirdAccountName": "深圳市汇庄金融服务有限公司",
          "thirdAccountId": "10972591",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "点点APP",
          "managerName": "申淼"
        }, {
          "id": 4028,
          "thirdName": "西安澄然金融信息服务有限公司",
          "alias": "西安澄然金融信息服务有限公司",
          "thirdLoginName": "10946511",
          "thirdAccountName": "西安澄然金融信息服务有限公司",
          "thirdAccountId": "10946511",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "万能钱包",
          "managerName": "贾荟"
        }, {
          "id": 4030,
          "thirdName": "广州荔支网络技术有限公司",
          "alias": "广州荔支网络技术有限公司",
          "thirdLoginName": "10993512",
          "thirdAccountName": "广州荔支网络技术有限公司",
          "thirdAccountId": "10993512",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "荔枝",
          "managerName": "李高敏"
        }, {
          "id": 4031,
          "thirdName": "广州荔支网络技术有限公司",
          "alias": "广州荔支网络技术有限公司",
          "thirdLoginName": "10993505",
          "thirdAccountName": "广州荔支网络技术有限公司",
          "thirdAccountId": "10993505",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "荔枝",
          "managerName": "李高敏"
        }, {
          "id": 4049,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "10991241",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "10991241",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "卡牛",
          "managerName": "张爽"
        }, {
          "id": 4057,
          "thirdName": "浙江挖财科技有限公司",
          "alias": "浙江挖财科技有限公司",
          "thirdLoginName": "11019822",
          "thirdAccountName": "浙江挖财科技有限公司",
          "thirdAccountId": "11019822",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "挖财信用卡管家"
        }, {
          "id": 4067,
          "thirdName": "深圳市随手科技有限公司",
          "alias": "深圳市随手科技有限公司",
          "thirdLoginName": "11048863",
          "thirdAccountName": "深圳市随手科技有限公司",
          "thirdAccountId": "11048863",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "随手记理财",
          "managerName": "申淼"
        }, {
          "id": 4072,
          "thirdName": "西藏美第奇互联网小额贷款有限公司",
          "alias": "西藏美第奇互联网小额贷款有限公司",
          "thirdLoginName": "11054712",
          "thirdAccountName": "西藏美第奇互联网小额贷款有限公司",
          "thirdAccountId": "11054712",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4080,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "11055113",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11055113",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "卡牛",
          "managerName": "张爽"
        }, {
          "id": 4092,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10955254",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10955254",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4115,
          "thirdName": "上海基分文化传播有限公司",
          "alias": "上海基分文化传播有限公司",
          "thirdLoginName": "11219560",
          "thirdAccountName": "上海基分文化传播有限公司",
          "thirdAccountId": "11219560",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "趣头条",
          "managerName": "申淼"
        }, {
          "id": 4116,
          "thirdName": "上海基分文化传播有限公司",
          "alias": "上海基分文化传播有限公司",
          "thirdLoginName": "11219552",
          "thirdAccountName": "上海基分文化传播有限公司",
          "thirdAccountId": "11219552",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "趣头条"
        }, {
          "id": 4173,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "11243621",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11243621",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "卡牛",
          "managerName": "张爽"
        }, {
          "id": 4178,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "11257906",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11257906",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4179,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "11243502",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11243502",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "卡牛",
          "managerName": "张爽"
        }, {
          "id": 4185,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "11257959",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11257959",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4198,
          "thirdName": "招联消费金融有限公司",
          "alias": "招联消费金融有限公司",
          "thirdLoginName": "11271790",
          "thirdAccountName": "招联消费金融有限公司",
          "thirdAccountId": "11271790",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4199,
          "thirdName": "招联消费金融有限公司",
          "alias": "招联消费金融有限公司",
          "thirdLoginName": "11271775",
          "thirdAccountName": "招联消费金融有限公司",
          "thirdAccountId": "11271775",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4200,
          "thirdName": "招联消费金融有限公司",
          "alias": "招联消费金融有限公司",
          "thirdLoginName": "11271763",
          "thirdAccountName": "招联消费金融有限公司",
          "thirdAccountId": "11271763",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4201,
          "thirdName": "招联消费金融有限公司",
          "alias": "招联消费金融有限公司",
          "thirdLoginName": "11271740",
          "thirdAccountName": "招联消费金融有限公司",
          "thirdAccountId": "11271740",
          "platformId": 34,
          "platformName": "广点通",
          "managerName": "申淼"
        }, {
          "id": 4202,
          "thirdName": "招联消费金融有限公司",
          "alias": "招联消费金融有限公司",
          "thirdLoginName": "11270292",
          "thirdAccountName": "招联消费金融有限公司",
          "thirdAccountId": "11270292",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4203,
          "thirdName": "北京展心展力信息科技有限公司",
          "alias": "北京展心展力信息科技有限公司",
          "thirdLoginName": "10977915",
          "thirdAccountName": "北京展心展力信息科技有限公司",
          "thirdAccountId": "10977915",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "233小游戏"
        }, {
          "id": 4227,
          "thirdName": "北京猿力未来科技有限公司",
          "alias": "北京猿力未来科技有限公司",
          "thirdLoginName": "11287800",
          "thirdAccountName": "北京猿力未来科技有限公司",
          "thirdAccountId": "11287800",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4237,
          "thirdName": "重庆市小米小额贷款有限公司",
          "alias": "重庆市小米小额贷款有限公司",
          "thirdLoginName": "11301583",
          "thirdAccountName": "重庆市小米小额贷款有限公司",
          "thirdAccountId": "11301583",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4241,
          "thirdName": "北京百传中云信息科技有限公司",
          "alias": "北京百传中云信息科技有限公司",
          "thirdLoginName": "11305252",
          "thirdAccountName": "北京百传中云信息科技有限公司",
          "thirdAccountId": "11305252",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4263,
          "thirdName": "北京天桐互动科技有限公司",
          "alias": "北京天桐互动科技有限公司",
          "thirdLoginName": "11321414",
          "thirdAccountName": "北京天桐互动科技有限公司",
          "thirdAccountId": "11321414",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "快点阅读"
        }, {
          "id": 4282,
          "thirdName": "深圳市卡牛科技有限公司",
          "alias": "深圳市卡牛科技有限公司",
          "thirdLoginName": "11330757",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11330757",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4312,
          "thirdName": "11352024",
          "thirdLoginName": "11352024",
          "thirdAccountName": "成都花漾科技有限公司",
          "thirdAccountId": "11352024",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "椒盐直综",
          "managerName": "胡新航"
        }, {
          "id": 4313,
          "thirdName": "睿智合创(北京)科技有限公司",
          "alias": "睿智合创(北京)科技有限公司",
          "thirdLoginName": "11317699",
          "thirdAccountName": "睿智合创(北京)科技有限公司",
          "thirdAccountId": "11317699",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4314,
          "thirdName": "四川花音科技有限公司",
          "alias": "四川花音科技有限公司",
          "thirdLoginName": "10895338",
          "thirdAccountName": "四川花音科技有限公司",
          "thirdAccountId": "10895338",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4315,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10886346",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10886346",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4316,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10886342",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10886342",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4317,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10886337",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10886337",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4318,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "10886322",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "10886322",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4319,
          "thirdName": "深圳众联商务有限公司",
          "alias": "深圳众联商务有限公司",
          "thirdLoginName": "10797768",
          "thirdAccountName": "深圳众联商务有限公司",
          "thirdAccountId": "10797768",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4320,
          "thirdName": "虎扑(上海)文化传播股份有限公司",
          "alias": "虎扑(上海)文化传播股份有限公司",
          "thirdLoginName": "10768936",
          "thirdAccountName": "虎扑(上海)文化传播股份有限公司",
          "thirdAccountId": "10768936",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4321,
          "thirdName": "上海欢兽实业有限公司",
          "alias": "上海欢兽实业有限公司",
          "thirdLoginName": "10762326",
          "thirdAccountName": "上海欢兽实业有限公司",
          "thirdAccountId": "10762326",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4322,
          "thirdName": "九江市云客网络小额贷款有限公司",
          "alias": "九江市云客网络小额贷款有限公司",
          "thirdLoginName": "10628701",
          "thirdAccountName": "九江市云客网络小额贷款有限公司",
          "thirdAccountId": "10628701",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4323,
          "thirdName": "北京大汉成吉科技发展有限公司",
          "alias": "北京大汉成吉科技发展有限公司",
          "thirdLoginName": "9980269",
          "thirdAccountName": "北京大汉成吉科技发展有限公司",
          "thirdAccountId": "9980269",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4324,
          "thirdName": "成都维仕小额贷款有限公司",
          "alias": "成都维仕小额贷款有限公司",
          "thirdLoginName": "9912062",
          "thirdAccountName": "成都维仕小额贷款有限公司",
          "thirdAccountId": "9912062",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4325,
          "thirdName": "优品汽车服务(上海)有限公司",
          "alias": "优品汽车服务(上海)有限公司",
          "thirdLoginName": "9834463",
          "thirdAccountName": "优品汽车服务(上海)有限公司",
          "thirdAccountId": "9834463",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4326,
          "thirdName": "上海静安维信小额贷款有限公司",
          "alias": "上海静安维信小额贷款有限公司",
          "thirdLoginName": "9805984",
          "thirdAccountName": "上海静安维信小额贷款有限公司",
          "thirdAccountId": "9805984",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4327,
          "thirdName": "深圳市和昌全景互联网金融服务有限公司",
          "alias": "深圳市和昌全景互联网金融服务有限公司",
          "thirdLoginName": "9714913",
          "thirdAccountName": "深圳市和昌全景互联网金融服务有限公司",
          "thirdAccountId": "9714913",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4328,
          "thirdName": "福州三六零网络小额贷款有限公司",
          "alias": "福州三六零网络小额贷款有限公司",
          "thirdLoginName": "9698670",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "9698670",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4329,
          "thirdName": "杭州艾米巴互联网金融信息服务有限公司",
          "alias": "杭州艾米巴互联网金融信息服务有限公司",
          "thirdLoginName": "9590244",
          "thirdAccountName": "杭州艾米巴互联网金融信息服务有限公司",
          "thirdAccountId": "9590244",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4346,
          "thirdName": "成都花漾科技有限公司",
          "alias": "成都花漾科技有限公司",
          "thirdLoginName": "11363413",
          "thirdAccountName": "成都花漾科技有限公司",
          "thirdAccountId": "11363413",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4356,
          "thirdName": "11369342",
          "thirdLoginName": "11369342",
          "thirdAccountName": "上海赢欢电子商务有限公司",
          "thirdAccountId": "11369342",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "哎呦有型"
        }, {
          "id": 4357,
          "thirdName": "上海赢欢电子商务有限公司",
          "alias": "上海赢欢电子商务有限公司",
          "thirdLoginName": "11369363",
          "thirdAccountName": "上海赢欢电子商务有限公司",
          "thirdAccountId": "11369363",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4374,
          "thirdName": "海南美高美网络科技有限公司",
          "alias": "海南美高美网络科技有限公司",
          "thirdLoginName": "11389572",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "11389572",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说"
        }, {
          "id": 4382,
          "thirdName": "杭州茂信商务咨询有限公司",
          "alias": "杭州茂信商务咨询有限公司",
          "thirdLoginName": "11391262",
          "thirdAccountName": "杭州茂信商务咨询有限公司",
          "thirdAccountId": "11391262",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "钱伴",
          "managerName": "申淼"
        }, {
          "id": 4391,
          "thirdName": "上海赢欢电子商务有限公司",
          "alias": "上海赢欢电子商务有限公司",
          "thirdLoginName": "11395865",
          "thirdAccountName": "上海赢欢电子商务有限公司",
          "thirdAccountId": "11395865",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4392,
          "thirdName": "上海赢欢电子商务有限公司",
          "alias": "上海赢欢电子商务有限公司",
          "thirdLoginName": "11395891",
          "thirdAccountName": "上海赢欢电子商务有限公司",
          "thirdAccountId": "11395891",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4395,
          "thirdName": "曲水萌屹网络科技有限公司",
          "alias": "曲水萌屹网络科技有限公司",
          "thirdLoginName": "11398965",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "11398965",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 4396,
          "thirdName": "合肥番茄金融信息服务有限公司",
          "alias": "合肥番茄金融信息服务有限公司",
          "thirdLoginName": "11399099",
          "thirdAccountName": "合肥番茄金融信息服务有限公司",
          "thirdAccountId": "11399099",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "易贷到"
        }, {
          "id": 4406,
          "thirdName": "11404061",
          "thirdLoginName": "11404061",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "11404061",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 4411,
          "thirdName": "11407486",
          "thirdLoginName": "11407486",
          "thirdAccountName": "北京快手科技有限公司",
          "thirdAccountId": "11407486",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "快手"
        }, {
          "id": 4412,
          "thirdName": "11407497",
          "thirdLoginName": "11407497",
          "thirdAccountName": "北京快手科技有限公司",
          "thirdAccountId": "11407497",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "快手"
        }, {
          "id": 4428,
          "thirdName": "11430801",
          "thirdLoginName": "11430801",
          "thirdAccountName": "北京密境和风科技有限公司",
          "thirdAccountId": "11430801",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "花椒直播",
          "managerName": "孟杨杨"
        }, {
          "id": 4431,
          "thirdName": "11434059",
          "thirdLoginName": "11434059",
          "thirdAccountName": "魔力红(深圳)网络科技有限公司",
          "thirdAccountId": "11434059",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "扎堆小说",
          "managerName": "胡新航"
        }, {
          "id": 4437,
          "thirdName": "合肥番茄金融信息服务有限公司",
          "alias": "合肥番茄金融信息服务有限公司",
          "thirdLoginName": "11439844",
          "thirdAccountName": "合肥番茄金融信息服务有限公司",
          "thirdAccountId": "11439844",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4438,
          "thirdName": "合肥番茄金融信息服务有限公司",
          "alias": "合肥番茄金融信息服务有限公司",
          "thirdLoginName": "11439871",
          "thirdAccountName": "合肥番茄金融信息服务有限公司",
          "thirdAccountId": "11439871",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "易贷到"
        }, {
          "id": 4442,
          "thirdName": "深圳前海众向互联网金融服务有限公司",
          "alias": "深圳前海众向互联网金融服务有限公司",
          "thirdLoginName": "11440878",
          "thirdAccountName": "深圳前海众向互联网金融服务有限公司",
          "thirdAccountId": "11440878",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4452,
          "thirdName": "11444979",
          "thirdLoginName": "11444979",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "11444979",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说"
        }, {
          "id": 4479,
          "thirdName": "11464741",
          "thirdLoginName": "11464741",
          "thirdAccountName": "魔力红(深圳)网络科技有限公司",
          "thirdAccountId": "11464741",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "小说帮",
          "managerName": "孟杨杨"
        }, {
          "id": 4481,
          "thirdName": "尚投金融信息服务(上海)有限公司",
          "alias": "尚投金融信息服务(上海)有限公司",
          "thirdLoginName": "11465903",
          "thirdAccountName": "尚投金融信息服务(上海)有限公司",
          "thirdAccountId": "11465903",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4493,
          "thirdName": "11468441",
          "thirdLoginName": "11468441",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "11468441",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "申淼"
        }, {
          "id": 4494,
          "thirdName": "魔法星空(北京)网络科技有限公司",
          "alias": "魔法星空(北京)网络科技有限公司",
          "thirdLoginName": "11470614",
          "thirdAccountName": "魔法星空(北京)网络科技有限公司",
          "thirdAccountId": "11470614",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4495,
          "thirdName": "魔法星空(北京)网络科技有限公司",
          "alias": "魔法星空(北京)网络科技有限公司",
          "thirdLoginName": "11470646",
          "thirdAccountName": "魔法星空(北京)网络科技有限公司",
          "thirdAccountId": "11470646",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4506,
          "thirdName": "上海欢兽实业有限公司",
          "alias": "上海欢兽实业有限公司",
          "thirdLoginName": "11481117",
          "thirdAccountName": "上海欢兽实业有限公司",
          "thirdAccountId": "11481117",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4518,
          "thirdName": "11487571",
          "thirdLoginName": "11487571",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "11487571",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "申淼"
        }, {
          "id": 4519,
          "thirdName": "11487663",
          "thirdLoginName": "11487663",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "11487663",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 4520,
          "thirdName": "11487692",
          "thirdLoginName": "11487692",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "11487692",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 4531,
          "thirdName": "11495268",
          "thirdLoginName": "11495268",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "11495268",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说",
          "managerName": "胡新航"
        }, {
          "id": 4534,
          "thirdName": "上海欢兽实业有限公司",
          "alias": "上海欢兽实业有限公司",
          "thirdLoginName": "11496024",
          "thirdAccountName": "上海欢兽实业有限公司",
          "thirdAccountId": "11496024",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4567,
          "thirdName": "郑州咏晟达生物科技有限公司",
          "alias": "郑州咏晟达生物科技有限公司",
          "thirdLoginName": "11508206",
          "thirdAccountName": "郑州咏晟达生物科技有限公司",
          "thirdAccountId": "11508206",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4596,
          "thirdName": "13980365",
          "thirdLoginName": "13980365",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "13980365",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "土耳其方块",
          "managerName": "申淼"
        }, {
          "id": 4608,
          "thirdName": "13987018",
          "thirdLoginName": "13987018",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "13987018",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "张爽"
        }, {
          "id": 4609,
          "thirdName": "13987053",
          "thirdLoginName": "13987053",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "13987053",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "张爽"
        }, {
          "id": 4644,
          "thirdName": "14006472",
          "thirdLoginName": "14006472",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14006472",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "张爽"
        }, {
          "id": 4645,
          "thirdName": "14006800",
          "thirdLoginName": "14006800",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14006800",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4646,
          "thirdName": "14006870",
          "thirdLoginName": "14006870",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14006870",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4647,
          "thirdName": "14006933",
          "thirdLoginName": "14006933",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14006933",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4648,
          "thirdName": "14006907",
          "thirdLoginName": "14006907",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14006907",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4649,
          "thirdName": "14007244",
          "thirdLoginName": "14007244",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007244",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4650,
          "thirdName": "14007290",
          "thirdLoginName": "14007290",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007290",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4651,
          "thirdName": "14007356",
          "thirdLoginName": "14007356",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007356",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4652,
          "thirdName": "14007414",
          "thirdLoginName": "14007414",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007414",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4653,
          "thirdName": "14007398",
          "thirdLoginName": "14007398",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007398",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4654,
          "thirdName": "14007437",
          "thirdLoginName": "14007437",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007437",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 4655,
          "thirdName": "14007529",
          "thirdLoginName": "14007529",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14007529",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4689,
          "thirdName": "14032876",
          "thirdLoginName": "14032876",
          "thirdAccountName": "珠海海鸟科技有限公司",
          "thirdAccountId": "14032876",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "运动赚",
          "managerName": "孟杨杨"
        }, {
          "id": 4700,
          "thirdName": "14040820",
          "thirdLoginName": "14040820",
          "thirdAccountName": "北京快手科技有限公司",
          "thirdAccountId": "14040820",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "快手"
        }, {
          "id": 4701,
          "thirdName": "14040777",
          "thirdLoginName": "14040777",
          "thirdAccountName": "北京快手科技有限公司",
          "thirdAccountId": "14040777",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "快手"
        }, {
          "id": 4715,
          "thirdName": "14048284",
          "thirdLoginName": "14048284",
          "thirdAccountName": "上海喜马拉雅科技有限公司",
          "thirdAccountId": "14048284",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "喜马拉雅",
          "managerName": "孟杨杨"
        }, {
          "id": 4731,
          "thirdName": "14055309",
          "thirdLoginName": "14055309",
          "thirdAccountName": "珠海海鸟科技有限公司",
          "thirdAccountId": "14055309",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "运动赚"
        }, {
          "id": 4755,
          "thirdName": "14062551",
          "thirdLoginName": "14062551",
          "thirdAccountName": "北京酷划在线网络技术有限公司",
          "thirdAccountId": "14062551",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "淘新闻",
          "managerName": "孟杨杨"
        }, {
          "id": 4757,
          "thirdName": "14063730",
          "thirdLoginName": "14063730",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14063730",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说",
          "managerName": "孟杨杨"
        }, {
          "id": 4770,
          "thirdName": "14068021",
          "thirdLoginName": "14068021",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14068021",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4771,
          "thirdName": "14068036",
          "thirdLoginName": "14068036",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14068036",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "申淼"
        }, {
          "id": 4790,
          "thirdName": "14072468",
          "thirdLoginName": "14072468",
          "thirdAccountName": "北京爱普优邦科技有限公司",
          "thirdAccountId": "14072468",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "iMoney",
          "managerName": "孟杨杨"
        }, {
          "id": 4835,
          "thirdName": "14132345",
          "thirdLoginName": "14132345",
          "thirdAccountName": "北京爱普优邦科技有限公司",
          "thirdAccountId": "14132345",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4845,
          "thirdName": "14138950",
          "thirdLoginName": "14138950",
          "thirdAccountName": "北京网聘咨询有限公司",
          "thirdAccountId": "14138950",
          "platformId": 34,
          "platformName": "广点通",
          "managerName": "孟杨杨"
        }, {
          "id": 4852,
          "thirdName": "14143303",
          "thirdLoginName": "14143303",
          "thirdAccountName": "北京爱普优邦科技有限公司",
          "thirdAccountId": "14143303",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4853,
          "thirdName": "14143320",
          "thirdLoginName": "14143320",
          "thirdAccountName": "北京爱普优邦科技有限公司",
          "thirdAccountId": "14143320",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4854,
          "thirdName": "14143346",
          "thirdLoginName": "14143346",
          "thirdAccountName": "北京爱普优邦科技有限公司",
          "thirdAccountId": "14143346",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4864,
          "thirdName": "14147403",
          "thirdLoginName": "14147403",
          "thirdAccountName": "马上消费金融股份有限公司",
          "thirdAccountId": "14147403",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4865,
          "thirdName": "14147372",
          "thirdLoginName": "14147372",
          "thirdAccountName": "马上消费金融股份有限公司",
          "thirdAccountId": "14147372",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4879,
          "thirdName": "14152447",
          "thirdLoginName": "14152447",
          "thirdAccountName": "南京大众书网图书文化有限公司",
          "thirdAccountId": "14152447",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4881,
          "thirdName": "14156243",
          "thirdLoginName": "14156243",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14156243",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4882,
          "thirdName": "14156363",
          "thirdLoginName": "14156363",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14156363",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说"
        }, {
          "id": 4885,
          "thirdName": "14157032",
          "thirdLoginName": "14157032",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14157032",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说",
          "managerName": "胡新航"
        }, {
          "id": 4886,
          "thirdName": "14157577",
          "thirdLoginName": "14157577",
          "thirdAccountName": "北京网聘咨询有限公司",
          "thirdAccountId": "14157577",
          "platformId": 34,
          "platformName": "广点通",
          "managerName": "孟杨杨"
        }, {
          "id": 4887,
          "thirdName": "14157635",
          "thirdLoginName": "14157635",
          "thirdAccountName": "四川花音科技有限公司",
          "thirdAccountId": "14157635",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4890,
          "thirdName": "14160850",
          "thirdLoginName": "14160850",
          "thirdAccountName": "北京酷赚技术有限公司",
          "thirdAccountId": "14160850",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4891,
          "thirdName": "14162571",
          "thirdLoginName": "14162571",
          "thirdAccountName": "四川花音科技有限公司",
          "thirdAccountId": "14162571",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4903,
          "thirdName": "14170180",
          "thirdLoginName": "14170180",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14170180",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 4904,
          "thirdName": "14170213",
          "thirdLoginName": "14170213",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14170213",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4905,
          "thirdName": "14170260",
          "thirdLoginName": "14170260",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14170260",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 4906,
          "thirdName": "14170237",
          "thirdLoginName": "14170237",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14170237",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条"
        }, {
          "id": 4907,
          "thirdName": "14170367",
          "thirdLoginName": "14170367",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14170367",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "360借条",
          "managerName": "杨利"
        }, {
          "id": 4921,
          "thirdName": "14179641",
          "thirdLoginName": "14179641",
          "thirdAccountName": "北京了了科技有限公司",
          "thirdAccountId": "14179641",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 5083,
          "thirdName": "14221104",
          "thirdLoginName": "14221104",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14221104",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "申淼"
        }, {
          "id": 5084,
          "thirdName": "14221105",
          "thirdLoginName": "14221105",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14221105",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "申淼"
        }, {
          "id": 5085,
          "thirdName": "14271285",
          "thirdLoginName": "14271285",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14271285",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 5086,
          "thirdName": "14271320",
          "thirdLoginName": "14271320",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14271320",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 5087,
          "thirdName": "14271323",
          "thirdLoginName": "14271323",
          "thirdAccountName": "曲水萌屹网络科技有限公司",
          "thirdAccountId": "14271323",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "步多多",
          "managerName": "孟杨杨"
        }, {
          "id": 5423,
          "thirdName": "11421084",
          "thirdLoginName": "11421084",
          "thirdAccountId": "11421084",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 5777,
          "thirdName": "14302136",
          "thirdLoginName": "14302136",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14302136",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说"
        }, {
          "id": 5855,
          "thirdName": "11257906",
          "thirdLoginName": "11257906",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11257906",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 5868,
          "thirdName": "11487663",
          "thirdLoginName": "11487663",
          "thirdAccountId": "11487663",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 5869,
          "thirdName": "11487571",
          "thirdLoginName": "11487571",
          "thirdAccountId": "11487571",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 5907,
          "thirdName": "14302162",
          "thirdLoginName": "14302162",
          "thirdAccountName": "海南美高美网络科技有限公司",
          "thirdAccountId": "14302162",
          "platformId": 34,
          "platformName": "广点通",
          "productName": "弓箭传说"
        }, {
          "id": 5923,
          "thirdName": "11257959",
          "thirdLoginName": "11257959",
          "thirdAccountName": "深圳市卡牛科技有限公司",
          "thirdAccountId": "11257959",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 5955,
          "thirdName": "14371323",
          "thirdLoginName": "14371323",
          "thirdAccountName": "福州三六零网络小额贷款有限公司",
          "thirdAccountId": "14371323",
          "platformId": 34,
          "platformName": "广点通"
        }, {
          "id": 14568,
          "thirdName": "14219449",
          "thirdLoginName": "14219449",
          "thirdAccountName": "招联消费金融有限公司",
          "thirdAccountId": "14219449",
          "platformId": 34,
          "platformName": "广点通"
        }],
      props: {
        key: "id",
        value: "thirdAccountId",
        label: "alais"
      },
      labelFn: this.showAccountName,
      pageSize: 2
    };
  },
  methods: {
    // 展示的账户信息
    showAccountName(item) {
      return (
        accountLabel(item) +
          `${item.thirdAccountId ? "(" + item.thirdAccountId + ")" : ""}`
      );
    }
  },
  components: {
    bcSelect
  }
};
</script>
<style scoped lang="less">
</style>
